### PR TITLE
use regex to find package name in blacklist

### PR DESCRIPTION
**Pull request by stiefel40k**
This eliminates the false positives, however it finds somehow more than it was before the change, so I might have to fix something

### CODE REVIEW

**Comment by vmavromatis** [comment]
Awesome! I will test it later, but I think it's a great improvement.

**Comment by vmavromatis** [comment]
Don't forget to add 're' under requirements

**Comment by stiefel40k** [comment]
fixed ;) but isn't re built into python?

**Comment by vmavromatis** [comment]
Hm maybe you are right. I will test later.

**Comment by stiefel40k** [comment]
now I had the time to play around, and I still have a 14% false positives. So stuff which is not installed, but got detected... what I was thinking, for the comparison, do we really need everything else after the first colon? Cos if not, we can just du what you suggested. Split at the first and leave the rest

**Comment by vmavromatis** [comment]
For the purpose of comparison, splitting and passing the first item should be enough. We can still print the full line later. Hey, thanks for the help ^_^

**Comment by stiefel40k** [comment]
ok, I changed it. First I used the regex, cos I was not sure what the other fields stand for. It looked like it could be an alternative name or something. 

> Hey, thanks for the help ^_^

no worries, happy to help ;)

**Comment by vmavromatis** [comment]
Great job @stiefel40k!

**Pull request merged**
