### PR TITLE
Do not fail on empty line

### PR DESCRIPTION
**Pull request by dopsi**
If line is empty, it cannot be split (raises IndexError)

### CODE REVIEW

**Comment by dopsi** [comment]
This is duplicate of #14, I didn't see it before making my PR.

**Comment by vmavromatis** [comment]
Merged #17 check if ok

**Comment by dopsi** [comment]
#17 fixed it. Thanks

**Comment by vmavromatis** [comment]
Great! many thanks for the contributions. Absolutely non-proprietary

**Pull request closed without merging**
