### PR TITLE
 CLI arguments, no prettytable, optional save to tempfile

### PR DESCRIPTION
**Pull request by KorvinSilver**
Removed the PrettyTable module and created argument handling without it.
Also, this version writes everything to a temporary file then prints the contents from there  
after disabling the line wrapping in the terminal.  
Then it prompts the user to save the file or not. Currently it just deletes the temp file if the answer is no or leaves it in /tmp if yes, and prints its location and suggests commands to view it from the command line.

The .idea in gitignore is there because I use PyCharm and it creates that directory.

Also reformatted the script to not have lines longer than 79 chars. (PEP 8)

I also replaced the install instructions in the readme because the cmd arguments make the sh script kinda pointless now. I could wrap it in still and have it also check for arguments but that'd be just redundant.

### CODE REVIEW

**Comment by stiefel40k** [comment]
if you have very long descriptions (like in case of `virtualbox` the folding of the long entry doesn't work, and so the alternative libraries won't show up.

the problem is most likely this:

https://github.com/KorvinSilver/absolutely-proprietary/blob/7317bd43a5e397889756ab0e54c80be1f1779b4c/main.py#L185-L197

**Comment by KorvinSilver** [comment]
That's not a problem, that's an intentional decision. New lines break the table formatting, and unless you want a strictly 79 characters long table, they're unnecessary anyway.

**Comment by KorvinSilver** [comment]
With PrettyTable it prints this with long lines when the terminal window's not big enough:  

screenshot from 2017-12-22 18-10-18

**Comment by stiefel40k** [comment]
ohh okay... I only use my terminal in full screen, so I never noticed that, my bad ^^ In this case it might make more sense to change the order of description and the alternatives, as it might make more sense to show how you can be "free" again, as the why something is not free... but it might be a matter of case.

However if you want to remove the newlines altogether, I would recommend to remove the call to the `format_entry`-method, as that what adds the newlines.

**Comment by KorvinSilver** [comment]
Now if I could add a new line after every alternative package but keep them in the same "cell"—so instead of a single line list, I'd have a multi line list—that'd be much better.

**Comment by stiefel40k** [comment]
You could iterate through the list of the alternatives (for this I would remove the `','.joint(alternatives)`), and for the first print the name, status and the description, and for every other just print an empty status, name and description along with the current alternative. And then the line Separator. So like:

```
    for item in stallman_disapproves:
        # print element
        first_line = True
        for alt in item[2]:
                if first_line:
                        f.write("| {:<{}} | {:<{}} | {:<{}} | {:<{}} |\n"
                                .format(item[0], package_len,
                                        item[1], status_len,
                                        alt, alternative_len,
                                        item[3], description_len))
                        first_line = False
                else:
                                                f.write("| {:<{}} | {:<{}} | {:<{}} | {:<{}} |\n"
                                .format(item[0], package_len,
                                        '', status_len,
                                        alt, alternative_len,
                                        '', description_len))
        # print horizontal separator
        f.write(line_separator(package_len,
                               status_len,
                               alternative_len,
                               description_len))
```

I think this could/should work

**Comment by vmavromatis** [comment]
lol guys what's going on here :dancing_men: If you're both happy with this I will merge! Looks cool especially the saving part. Awesome stuff!

**Comment by stiefel40k** [comment]
the only part I'm wondering is, that I think the part with `elif len(item[2]) == 1:` (line 202) is imho unnecessary. I mean it could be merged into the len > 1 part. Or @KorvinSilver is there any special case I'm not seeing?

**Comment by KorvinSilver** [comment]
Well yeah, it started out as replacing PrettyTable and now it writes files. In my opinion, for a terminal based script, it's a better approach when long lines can break the output. And this way you don't need to redirect all the output of the script to save the table. And the actual printout of the table can always be modified, even to the point where it stays with it like the `less` command does with files, or remove it entirely. It's just one line in the script at the moment.

**Comment by KorvinSilver** [comment]
Yeah, you're right, that's redundant, > 0 would do what's needed.

**Comment by KorvinSilver** [comment]
The only thing I couldn't figure out is how to sort the alternatives in a way that rows with no alternatives go after rows with alternatives. Nothing is before any character by default and the built-in sort() can't change it as far as I know. Maybe a more complex lambda function but I for now I'm done with it. That part can be always changed later if needed.

**Comment by KorvinSilver** [comment]
I woke up and thought: _"I should save the output as a markdown table"_. So I added an option to do just that. And now I'm done with this pull request. 15 commits, wow.  
Merge, don't merge, copy what's useful and throw away what's not, up to you.

**Comment by vmavromatis** [comment]
Wow at 15 commits haha. For me, the markdown save with default name is not working (custom name works). I'm trying to debug and see that maybe .md is not appended properly or something gets messed up at L245. I will try to see what.

**Comment by stiefel40k** [comment]
the problem resides in line 251 and 262. If you use the original name is used (or the user doesn't have permission) the `new_file` variable is set to be `tmp_file`, however in line 262 we only write out things if `new_file != tmp_file`, meaning if you don't set the name, than it won't write out anything.

**Comment by KorvinSilver** [comment]
The try-except block starting on line 256 doesn't necessarily give back PermissionError. It creates the dir if needed, but if that already exists, it won't check if the user has write permission, ie. it won't write anything at that point to that directory. But it can change new_line if the user doesn't have rights to access the directory specified. The block starting on line 262 writes the actual file.

**Comment by vmavromatis** [comment]
This is completely off-topic but I just found a cool way to get all PRs locally (https://gist.github.com/piscisaureus/3342247) rather than type the whole git fetch blabla you just add this and then `git fetch origin`. Just thought you guys should know if you don't already.

**Comment by stiefel40k** [comment]
> it won't write anything at that point to that directory.

ahh yeah, you are right. Sorry I overlooked that part :)

**Comment by vmavromatis** [comment]
Looks fine.

**Pull request merged**
